import debug from 'debug'

export const logApp = debug('rts-app')
export const logLayout = debug('rts-layout')
export const logPointerEvent = debug('rts-pointer-event')
export const logDoubleTapEvent = debug('rts-double-tap-event')
export const logHitboxes = debug('rts-hitboxes')
export const logGrid = debug('rts-grid')
export const logItemBounds = debug('rts-item-bounds')
export const logSideBar = debug('rts-side-bar')
export const logAI = debug('rts-ai')
export const logNoFog = debug('rts-no-fog')
export const logNoSightHide = debug('rts-no-sight-hide')
export const logCash = debug('rts-cash')
export const logWebsocket = debug('rts-websocket')
