export enum ECommandName {
  deselect = 'deselect',
  moveFollow = 'moveFollow',
  attack = 'attack',
  attackGuard = 'attackGuard',
  patrol = 'patrol',
  deploy = 'deploy',
  buildTurret = 'buildTurret',
  buildStarport = 'buildStarport',
  constructSCV = 'constructSCV',
  constructHarvester = 'constructHarvester',
  constructScoutTank = 'constructScoutTank',
  constructHeavyTank = 'constructHeavyTank',
  constructChopper = 'constructChopper',
  constructWraith = 'constructWraith',
}
